In [12]:
print('Lou revised')

hi


In [11]:
import numpy as np

- 일반적으로 행렬만들기

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [3]:
B = np.array([
    [0,1],
    [-1,3],
    [5,2],
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

- 0~1까지의 랜덤값을 행렬로 만들기

In [4]:
C = np.random.rand(3,5)
C

array([[0.46316454, 0.78220418, 0.69091239, 0.15664587, 0.80701587],
       [0.83720161, 0.65351167, 0.16287523, 0.69809686, 0.16369816],
       [0.3755402 , 0.11617013, 0.32614265, 0.78564295, 0.98972189]])

- 0을 행렬로 만들기

In [5]:
D = np.zeros((2,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- 행렬의 원소를 가져올때(2행, 3열)

In [6]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [7]:
A[0][2]

2

In [8]:
2*A

array([[ 2, -2,  4],
       [ 6,  4,  4],
       [ 8,  2,  4],
       [14, 10, 12]])

## 실습과제 _ numpy행렬연습

$$\left[\begin{array}{rrr} 
0&1&-1\\
1&2&3\\
2&1&0\\
-1&2&-4
\end{array}\right]$$
를 "A"로 정의

$$\left[\begin{array}{rrr} 
0&2\\
1&1\\
-1&-2
\end{array}\right]$$
를 "B"로 정의해보세요

- 정의한 행렬 AA 의 2 행 2 열 원소에 접근해보세요.
- 정의한 행렬 AA 의 4 행 1열 원소에 접근해보세요.

In [9]:
import numpy as np

# 1: 행렬 A를 정의해보세요
A = np.array([
    [0,1,-1],
    [1,2,3],
    [2,1,0],
    [-1,2,-4]
    ])

# 2: 행렬 B를 정의해보세요
B = np.array([
    [0,2],
    [1,1],
    [-1,-2]
    ])

print(A)
print(B)
print(A[1][1])  # 3: 여기서 A의 2행 2열 원소에 접근해보세요
print(A[3][0])  # 4: 여기서 A의 4행 1열 원소에 접근해보세요

[[ 0  1 -1]
 [ 1  2  3]
 [ 2  1  0]
 [-1  2 -4]]
[[ 0  2]
 [ 1  1]
 [-1 -2]]
2
-1


In [10]:

import numpy as np

A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

# 행렬 연산 결과를 result에 저장하세요
result = (2*A)@(-1*B)*((3*C)+D)
result

array([[ -22,   16],
       [ 112, -162]])